console.log("Welcome to the new page")
// Arithmetic Operators

let num1 = 4
let num2 = 2
let result = num1 + num2 //do the same for (%,*,-,/)

console.log(result)

let bool1 = true
let bool2 = true
let outcome = bool1 + bool2

console.log(outcome) //0-false,1-true

//concantenating
let numb = 4
numb += 2 // numb +2
console.log(numb)

// increment & Decrement ++, --

// Pre-Increment
let numa = 4
let a = ++numa
console.log(a,numa)

// Post-Icrement
let numc = 4
let c = ++numa
console.log(c,numc)

// Dealing with powers
let val1 = 4
let result1 = val1*3
console.log(result1)