// This is a great JS Review
console.log("Hello World")

console.log(2+2)

// Variables
let num = 3+3
console.log("Total of Num =",num)

// Naming
let user_name = "Godwin"
console.log("My name is ",user_name)

// Area Of a Circle
let r = 5
const pi = 3.14

area = pi*r*r
console.log("The area of the Circle is ",area,"square units")

// Data Types In JavaScript
// Number
// String
// Booleans
// Null
// Undefined

// Number
let num1 = 23456
console.log(num1,typeof num1)

// Strings
let names = "Godwin Ofwono"
console.log(names + " Edward",typeof names)

// Booleans
let bool = 5> 7
console.log(typeof bool)

// undefined
let user1 
console.log(typeof user1)

// Converting data Types from One type to another
let numx = 6
console.log(numx,typeof numx)

let numy = String(6)
console.log(numy,typeof numy)

let numz = Number("123")
console.log(numz,typeof numz)

let name1 = Boolean("Godwin")
console.log(name1, typeof name1)

let z = parseInt("123 Navin")
console.log(z,typeof z)